### Fifth task
\begin{equation*}
 \begin{cases}
   y_1' = -125y_1 + 123.1y_2,\\
   y_1' = 123.1y_1 - 123y_2, &y_1(0) = 1, y_2(0) = 1
 \end{cases}
\end{equation*}

In [1]:
import pandas as pd
from numpy import linalg as LA
import numpy as np
from scipy.integrate import odeint

In [15]:
A = np.array([[-125, 123.1],
               [123.1, 123]])
h, h1, h2 = 0.1, 0.05, 0.001
t1, t2 = 0, 0.5
y0 = [1, 1]

1. Построить на промежутке [0, 0.5] точное решение в точках $t_i = ih, i = 1, 2, . . . , 5, h = 0.1$

In [14]:
def pend(y, t, b, c):
    theta, omega = y
    result = [-125*theta + 123.1*omega, b*theta - c*omega]
    return result


y0 = [1, 1]
b = 123.1
c = 123
t = np.linspace(0, 0.6, 6)
sol = odeint(pend, y0, t, args=(b, c))

y1 = [0]*len(sol)
y2 = [0]*len(sol)

for i in range(len(sol)):
    y1[i] = sol[i][0]
    y2[i] = sol[i][1]

точное решение в точках $t_i = ih, i = 1, 2, . . . , 5, h = 0.1$

In [12]:
y1

[1.0,
 0.8944028273424263,
 0.8032320570839919,
 0.7213547597253034,
 0.6478236003387385,
 0.5817878484017752]

In [13]:
y2

[1.0,
 0.9016979614029801,
 0.8097835963332589,
 0.7272384695626517,
 0.6531075552380741,
 0.5865331845363165]

2. Построить на промежутке [0, 0.5] приближенное решение в тех же точках с шагом h = 0.05

а) Явный метод Эйлера.

In [5]:
def Euler(A, t1, t2, h0, h, y0):
    n, m = A.shape
    E = np.eye(n)
    W = E + A * h
    size = int((t2 - t1) / h) + 1
    y = [[0] * m for i in range(size)]
    y[0] = y0
    for i in np.arange(1, len(y)):
        y[i] = W.dot(y[i - 1])

    k = int(h0/h)

    res1 = [y[i][0] for i in range(0, len(y), k)]
    res2 = [y[i][1] for i in range(0, len(y), k)]
    return res1, res2

In [25]:
xx = [round(x, 2) for x in np.arange(0, 0.6, 0.1)]

w, v = LA.eig(A)      
a = max(abs(w))
print("Наибольшое с.ч. матрицы А = ", a)
print("Условие устойчивости выполняется только при работе с h = 0.001")
result1_1, result1_2 = Euler(A, t1, t2,h, h1, y0)     #h=0.05
blind = [" "]*len(xx)
errs1_1 = [y1[i] - result1_1[i] for i in range(len(xx))]
errs1_2 = [y2[i] - result1_2[i] for i in range(len(xx))]
result1_1_1, result1_2_2 = Euler(A, t1, t2, h, h2, y0)       #h=0.001
errs1_1_1 = [y1[i] - result1_1_1[i] for i in range(len(xx))]
errs1_2_2 = [y2[i] - result1_2_2[i] for i in range(len(xx))]

data = [blind, result1_1, result1_2, errs1_1, errs1_2, blind, result1_1_1, result1_2_2, errs1_1_1, errs1_2_2]
indexes = [
    "h = 0.05",
    "y1",
    "y2",
    "y1* - y1",
    "y2* - y2",
    "h = 0.001",
    "y1",
    "y2",
    "y1* - y1",
    "y2* - y2"]
df1 = pd.DataFrame(data, index = indexes, columns=xx)
df1.columns.name = "$x$"
df1

Наибольшое с.ч. матрицы А =  175.7272445842376
Условие устойчивости выполняется только при работе с h = 0.001

$x$       0.0          0.1          0.2          0.3          0.4          0.5
h = 0.05
y1          1       77.141      6226.26       522855  4.53391e+07  4.02855e+09
y2          1      100.701      9865.17       950878  9.07489e+07  8.60746e+09
y1* - y1    0     -76.2466     -6225.46      -522855 -4.53391e+07 -4.02855e+09
y2* - y2    0     -99.7993     -9864.36      -950877 -9.07489e+07 -8.60746e+09
h = 0.001
y1          1  4.50242e+06  4.07534e+13  3.68878e+20  3.33888e+27  3.02218e+34
y2          1   1.0926e+07  9.88965e+13  8.95158e+20  8.10248e+27  7.33393e+34
y1* - y1    0 -4.50242e+06 -4.07534e+13 -3.68878e+20 -3.33888e+27 -3.02218e+34
y2* - y2    0  -1.0926e+07 -9.88965e+13 -8.95158e+20 -8.10248e+27 -7.33393e+34

б) Неявный метод Эйлера.

In [26]:
def Rev_Euler(A, t1, t2, h0, h, y0):
    n, m = A.shape
    E = np.eye(n)
    W = E - A * h
    W = LA.inv(W)

    size = int((t2 - t1) / h) + 1
    y = [[0] * m for i in range(size)]
    y[0] = y0
    for i in np.arange(1, len(y)):
        y[i] = W.dot(y[i - 1])

    k = int(h0 / h)

    res1 = [y[i][0] for i in range(0, len(y), k)]
    res2 = [y[i][1] for i in range(0, len(y), k)]
    return res1, res2

In [27]:
result2_1, result2_2 = Rev_Euler(A, t1, t2, h, h1, y0)    #h=0.05
errs2_1 = [y1[i] - result2_1[i] for i in range(len(xx))]
errs2_2 = [y2[i] - result2_2[i] for i in range(len(xx))]
result2_1_1, result2_2_2 = Rev_Euler(A, t1, t2, h, h2, y0)    #h=0.001
errs2_1_1 = [y1[i] - result2_1_1[i] for i in range(len(xx))]
errs2_2_2 = [y2[i] - result2_2_2[i] for i in range(len(xx))]

data = [blind, result2_1, result2_2, errs2_1, errs2_2, blind, result2_1_1, result2_2_2, errs2_1_1, errs2_2_2]
df = pd.DataFrame(data, index = indexes, columns=xx)
df.columns.name = "$x$"
df

$x$       0.0          0.1          0.2          0.3          0.4          0.5
h = 0.05
y1          1    0.0136671  0.000197301  2.98424e-06  4.68017e-08  7.53437e-10
y2          1    0.0182692   0.00032325  5.61779e-06  9.66164e-08  1.65131e-09
y1* - y1    0     0.880736     0.803035     0.721352     0.647824     0.581788
y2* - y2    0     0.883429      0.80946     0.727233     0.653107     0.586533
h = 0.001
y1          1  9.64681e+07  1.87086e+16  3.62825e+24  7.03646e+32  1.36462e+41
y2          1    2.341e+08  4.54002e+16  8.80469e+24  1.70754e+33  3.31152e+41
y1* - y1    0 -9.64681e+07 -1.87086e+16 -3.62825e+24 -7.03646e+32 -1.36462e+41
y2* - y2    0   -2.341e+08 -4.54002e+16 -8.80469e+24 -1.70754e+33 -3.31152e+41

в) Интерполяционный метод Адамса второго порядка.

In [9]:
def Adams(A, t1, t2, h0, h, y0, y1):
    n, m = A.shape
    E = np.eye(n)

    size = int((t2 - t1) / h) + 1
    y = [[0] * m for i in range(size)]
    y[0] = y0
    y[1] = y1
    for i in np.arange(2, len(y)):
        y[i] = (E + 3*h*A/2).dot(y[i-1]) - (h*A/2).dot(y[i-2])

    k = int(h0 / h)

    res1 = [y[i][0] for i in range(0, len(y), k)]
    res2 = [y[i][1] for i in range(0, len(y), k)]
    return res1, res2

In [28]:
Y0 = [1, 1]
Y1 = [result2_1[1], result2_2[1]]
result3_1, result3_2 = Adams(A, t1, t2, h, h1, Y0, Y1)    # шаг h=0.05
errs3_1 = [y1[i] - result3_1[i] for i in range(len(xx))]
errs3_2 = [y2[i] - result3_2[i] for i in range(len(xx))]
result3_1_1, result3_2_2 = Adams(A, t1, t2, h, h2, Y0, Y1)    #h=0.001
errs3_1_1 = [y1[i] - result3_1_1[i] for i in range(len(xx))]
errs3_2_2 = [y2[i] - result3_2_2[i] for i in range(len(xx))]

print("Условие устойчивости выполняется только при работе с h = 0.001")

data = [blind, result3_1, result3_2, errs3_1, errs3_2, blind, result3_1_1, result3_2_2, errs3_1_1, errs3_2_2]
df = pd.DataFrame(data, index = indexes, columns=xx)
df.columns.name = "$x$"
df

Условие устойчивости выполняется только при работе с h = 0.001

$x$       0.0          0.1          0.2          0.3          0.4          0.5
h = 0.05
y1          1     0.101708     -66.4411     -22650.4  -5.8535e+06 -1.35101e+09
y2          1     -5.83952     -1090.03      -200788 -3.70995e+07 -6.87309e+09
y1* - y1    0     0.792694      67.2443      22651.1   5.8535e+06  1.35101e+09
y2* - y2    0      6.74121      1090.84       200789  3.70995e+07  6.87309e+09
h = 0.001
y1          1      -725755 -2.09852e+13 -6.06786e+20 -1.75452e+28 -5.07319e+35
y2          1 -1.76119e+06 -5.09248e+13 -1.47249e+21  -4.2577e+28 -1.23111e+36
y1* - y1    0       725756  2.09852e+13  6.06786e+20  1.75452e+28  5.07319e+35
y2* - y2    0  1.76119e+06  5.09248e+13  1.47249e+21   4.2577e+28  1.23111e+36