### Sixth task

$-\frac{1}{3 + x}u''+xu'+ln(x+2)u = 1 − \frac{x}{2},$
$ u'(-1)=u'(1)+\frac{1}{2}u(1)=0$

In [1]:
import numpy as np
import pandas as pd

1) Для реализации алгоритма метода прогонки следует создать модуль с процедурой, параметрами которой должны являться порядок системы, массивы коэффициентов A, B, C, G. Результатом должен быть массив решения Y в точках сетки.

In [2]:
def method_1(p, q, r, f, a1, a2, b1, b2, a, b, x_0, x_1, n):
    h = round((x_1 - x_0) / n, 3)
    xx = [round(i, 3) for i in np.arange(x_0, x_1 + h, h)]
    A, B, C, G = [0] * (n + 1), [0] * (n + 1), [0] * (n + 1), [0] * (n + 1)

    B[0] = -a1 - a2 / h
    C[0] = -a2 / h
    G[0] = a

    A[n] = -b2 / h
    B[n] = -b1 - b2 / h
    G[n] = b

    for i in range(1, n):
        A[i] = -p(xx[i]) / h ** 2 - q(xx[i]) / (2 * h)
        B[i] = - r(xx[i]) - 2 * p(xx[i]) / h ** 2
        C[i] = q(xx[i]) / (2 * h) - p(xx[i]) / h ** 2
        G[i] = f(xx[i])

    s, t = [0]*(n+1), [0]*(n+1)
    for i in range(n+1):
        if i == 0:
            s[i] = C[i]/B[i]
            t[i] = -G[i]/B[i]
        else:
            s[i] = C[i]/(B[i] - A[i]*s[i-1])
            t[i] = (A[i]*t[i-1] - G[i])/(B[i] - A[i]*s[i-1])
    y = [0]*(n+1)
    y[n] = t[n]
    for i in range(n-1, -1, -1):
        y[i] = s[i]*y[i+1] + t[i]
    return xx, y

2) Получить “точное” решение задачи в узлах основной сетки, обозначим его Yex.

In [9]:
xx = [round(x, 3) for x in np.arange(-1, 1.1, 0.1)]

arr = [2.9275,
2.9124,
2.8671,
2.7849,
2.6881,
2.5395,
2.4048,
2.2330,
2.0476,
1.8545,
1.6598,
1.5127,
1.2893,
1.1239,
0.9767,
0.8650,
0.7444,
0.6655,
0.5944,
0.5467,
0.5142]
indexes = ["Y_ex"]
df = pd.DataFrame(arr, index = xx, columns = indexes).T
df.columns.name = "x"
df

x,-1.0,-0.9,-0.8,-0.7,-0.6,-0.5,-0.4,-0.3,-0.2,-0.1,...,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0
Y_ex,2.9275,2.9124,2.8671,2.7849,2.6881,2.5395,2.4048,2.233,2.0476,1.8545,...,1.5127,1.2893,1.1239,0.9767,0.865,0.7444,0.6655,0.5944,0.5467,0.5142

3) Получить решение с порядком O(h) при n = 10. Результаты оформить в виде таблицы

In [4]:
a1, a2, b1, b2, a, b = 0, -1, 1/2, 1, 0, 0
x_0 = -1
x_n = 1

# определим функции данного уравнения

def p(x):
    return 1/(x+3)
def q(x):
    return -x
def r(x):
    return np.log(2 + x)
def f(x):
    return 1 - x/2

In [16]:
n = 10
xx, yy = method_1(p, q, r, f,a1, a2, b1, b2, a, b, x_0, x_n, n)
errs_1 = np.zeros(n+1)
for i in range(n+1):
    errs_1[i] = np.abs(yy[i] - arr[i*2])
data = [yy, errs_1]
indexes = ["y", "|y - y_ex|"]
df = pd.DataFrame(data,index = indexes, columns= xx)
df.columns.name = "x"
df

x,-1.0,-0.8,-0.6,-0.4,-0.2,-0.0,0.2,0.4,0.6,0.8,1.0
y,2.382635,2.382635,2.279513,2.08192,1.812748,1.507548,1.207742,0.95029,0.758306,0.637436,0.579487
|y - y_ex|,0.544865,0.484465,0.408587,0.32288,0.234852,0.152252,0.081558,0.02641,0.013906,0.043036,0.065287

In [15]:
n = 20
xx, yy = method_1(p, q, r, f,a1, a2, b1, b2, a, b, x_0, x_n, n)
errs_2 = [0]*(n+1)
for i in range(n+1):
    errs_2[i] = np.abs(yy[i] - arr[i])
data = [yy, errs_2]
indexes = ["y", "|y - y_ex|"]
df = pd.DataFrame(data,index = indexes, columns= xx)
df.columns.name = "x"
df

x,-1.0,-0.9,-0.8,-0.7,-0.6,-0.5,-0.4,-0.3,-0.2,-0.1,...,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0
y,2.630558,2.630558,2.602744,2.547239,2.464963,2.357749,2.2284,2.080674,1.919184,1.7492,...,1.406286,1.244261,1.094797,0.961377,0.846273,0.75051,0.673972,0.615621,0.573785,0.546462
|y - y_ex|,0.296942,0.281842,0.264356,0.237661,0.223137,0.181751,0.1764,0.152326,0.128416,0.1053,...,0.106414,0.045039,0.029103,0.015323,0.018727,0.00611,0.008472,0.021221,0.027085,0.032262

Получить решение с O(h^2) при n = 10.

In [13]:
# порядок погрешности O(h^2)
def method_2(p, q, r, f, a1, a2, b1, b2, a, b, x_0, x_1, n):
    h = round((x_1 - x_0) / n, 3)
    xx = [0]*(n+2)
    for i in range(n+2):
        xx[i] = round(x_0 - h/2 +i*h,3)
    A, B, C, G = [0] * (n + 2), [0] * (n + 2), [0] * (n + 2), [0] * (n + 2)

    B[0] = -a1/2 -a2/h
    C[0] = a1/2 - a2/h
    G[0] = a

    A[n+1] = b1/2 - b2/h
    B[n+1] = -b1/2 - b2/h
    G[n+1] = b

    for i in range(1, n+1):
        A[i] = -p(xx[i]) / h ** 2 - q(xx[i]) / (2 * h)
        B[i] = - r(xx[i]) - 2 * p(xx[i]) / h ** 2
        C[i] = q(xx[i]) / (2 * h) - p(xx[i]) / h ** 2
        G[i] = f(xx[i])

    s, t = [0] * (n + 2), [0] * (n + 2)
    for i in range(n + 2):
        if i == 0:
            s[i] = C[i] / B[i]
            t[i] = -G[i] / B[i]
        else:
            s[i] = C[i] / (B[i] - A[i] * s[i - 1])
            t[i] = (A[i] * t[i - 1] - G[i]) / (B[i] - A[i] * s[i - 1])
    y = [0] * (n + 2)
    y[n+1] = t[n+1]
    for i in range(n, -1, -1):
        y[i] = s[i] * y[i + 1] + t[i]
    return xx, y

In [18]:
n = 10
xx, yy = method_2(p, q, r, f,a1, a2, b1, b2, a, b, x_0, x_n, n)
errs_3 = [0]*(n)

for i in range(n):
    errs_3[i] = np.abs(yy[i+1] - arr[2*(i) + 1])


yy = [yy[i] for i in range(1, n+1)]
xx = [xx[i] for i in range(1, n+1)]

data = [yy, errs_3]
indexes = ["y", "|y - y_ex|"]
df = pd.DataFrame(data,index = indexes, columns= xx)
df.columns.name = "x"
df

x,-0.9,-0.7,-0.5,-0.3,-0.1,0.1,0.3,0.5,0.7,0.9
y,2.916409,2.795015,2.559407,2.232227,1.851423,1.464401,1.117069,0.841972,0.651379,0.538849
|y - y_ex|,0.004009,0.010115,0.019907,0.000773,0.003077,0.048299,0.006831,0.023028,0.014121,0.007851